/*
 * Floorp OS Local HTTP Server API
 *
 * Floorp OS Local HTTP Server provides a minimal subset of os-apis to other local applications via HTTP/JSON. - Loopback-only server (127.0.0.1) - Optional bearer token authentication (disabled by default) - Exposes browser information, web scraping, and tab management capabilities 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DispatchEventRequest {
    /// Element fingerprint
    #[serde(rename = "fingerprint")]
    pub fingerprint: String,
    /// Event type to dispatch (e.g., 'click', 'input', 'change')
    #[serde(rename = "eventType")]
    pub event_type: String,
    #[serde(rename = "options", skip_serializing_if = "Option::is_none")]
    pub options: Option<Box<models::DispatchEventRequestOptions>>,
}

impl DispatchEventRequest {
    pub fn new(fingerprint: String, event_type: String) -> DispatchEventRequest {
        DispatchEventRequest {
            fingerprint,
            event_type,
            options: None,
        }
    }
}

