/*
 * Floorp OS Local HTTP Server API
 *
 * Floorp OS Local HTTP Server provides a minimal subset of os-apis to other local applications via HTTP/JSON. - Loopback-only server (127.0.0.1) - Optional bearer token authentication (disabled by default) - Exposes browser information, web scraping, and tab management capabilities 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InputRequest {
    /// CSS selector for the input element
    #[serde(rename = "selector")]
    pub selector: String,
    /// Value to type
    #[serde(rename = "value")]
    pub value: String,
    /// Whether to simulate typing character by character
    #[serde(rename = "typingMode", skip_serializing_if = "Option::is_none")]
    pub typing_mode: Option<bool>,
    /// Delay between keystrokes in milliseconds
    #[serde(rename = "typingDelayMs", skip_serializing_if = "Option::is_none")]
    pub typing_delay_ms: Option<i32>,
}

impl InputRequest {
    pub fn new(selector: String, value: String) -> InputRequest {
        InputRequest {
            selector,
            value,
            typing_mode: None,
            typing_delay_ms: None,
        }
    }
}

