/*
 * Floorp OS Local HTTP Server API
 *
 * Floorp OS Local HTTP Server provides a minimal subset of os-apis to other local applications via HTTP/JSON. - Loopback-only server (127.0.0.1) - Optional bearer token authentication (disabled by default) - Exposes browser information, web scraping, and tab management capabilities 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize, Deserializer};

/// Deserialize null as false
fn deserialize_bool_or_null<'de, D>(deserializer: D) -> Result<bool, D::Error>
where
    D: Deserializer<'de>,
{
    Option::<bool>::deserialize(deserializer).map(|opt| opt.unwrap_or(false))
}

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OkResponse {
    #[serde(rename = "ok", default, deserialize_with = "deserialize_bool_or_null")]
    pub ok: bool,
}

impl OkResponse {
    pub fn new(ok: bool) -> OkResponse {
        OkResponse {
            ok,
        }
    }
}

