/*
 * Floorp OS Local HTTP Server API
 *
 * Floorp OS Local HTTP Server provides a minimal subset of os-apis to other local applications via HTTP/JSON. - Loopback-only server (127.0.0.1) - Optional bearer token authentication (disabled by default) - Exposes browser information, web scraping, and tab management capabilities 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SetInnerHtmlRequest {
    /// CSS selector for the element
    #[serde(rename = "selector")]
    pub selector: String,
    /// HTML content to set
    #[serde(rename = "html")]
    pub html: String,
}

impl SetInnerHtmlRequest {
    pub fn new(selector: String, html: String) -> SetInnerHtmlRequest {
        SetInnerHtmlRequest {
            selector,
            html,
        }
    }
}

