/*
 * Floorp OS Local HTTP Server API
 *
 * Floorp OS Local HTTP Server provides a minimal subset of os-apis to other local applications via HTTP/JSON. - Loopback-only server (127.0.0.1) - Optional bearer token authentication (disabled by default) - Exposes browser information, web scraping, and tab management capabilities
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SwitchWorkspaceResponse : Response after switching workspace
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SwitchWorkspaceResponse {
    /// Whether the switch was successful
    #[serde(rename = "success")]
    pub success: bool,
    /// ID of the workspace after the switch
    #[serde(
        rename = "workspaceId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub workspace_id: Option<Option<uuid::Uuid>>,
}

impl SwitchWorkspaceResponse {
    /// Response after switching workspace
    pub fn new(success: bool) -> SwitchWorkspaceResponse {
        SwitchWorkspaceResponse {
            success,
            workspace_id: None,
        }
    }
}
