/*
 * Floorp OS Local HTTP Server API
 *
 * Floorp OS Local HTTP Server provides a minimal subset of os-apis to other local applications via HTTP/JSON. - Loopback-only server (127.0.0.1) - Optional bearer token authentication (disabled by default) - Exposes browser information, web scraping, and tab management capabilities 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UploadFileRequest {
    /// CSS selector for the file input element
    #[serde(rename = "selector")]
    pub selector: String,
    /// Absolute path to the file to upload
    #[serde(rename = "filePath")]
    pub file_path: String,
}

impl UploadFileRequest {
    pub fn new(selector: String, file_path: String) -> UploadFileRequest {
        UploadFileRequest {
            selector,
            file_path,
        }
    }
}

