/*
 * Floorp OS Local HTTP Server API
 *
 * Floorp OS Local HTTP Server provides a minimal subset of os-apis to other local applications via HTTP/JSON. - Loopback-only server (127.0.0.1) - Optional bearer token authentication (disabled by default) - Exposes browser information, web scraping, and tab management capabilities 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WorkspaceInfo : Information about a single workspace
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkspaceInfo {
    /// Unique identifier for the workspace
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    /// Display name of the workspace
    #[serde(rename = "name")]
    pub name: String,
    /// Icon identifier for the workspace
    #[serde(rename = "icon", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub icon: Option<Option<String>>,
    /// Container/user context ID associated with the workspace
    #[serde(rename = "userContextId")]
    pub user_context_id: i32,
    /// Whether this is the default workspace
    #[serde(rename = "isDefault")]
    pub is_default: bool,
    /// Whether this workspace is currently selected
    #[serde(rename = "isSelected")]
    pub is_selected: bool,
}

impl WorkspaceInfo {
    /// Information about a single workspace
    pub fn new(id: uuid::Uuid, name: String, user_context_id: i32, is_default: bool, is_selected: bool) -> WorkspaceInfo {
        WorkspaceInfo {
            id,
            name,
            icon: None,
            user_context_id,
            is_default,
            is_selected,
        }
    }
}

